CUSTOM_SHOP_DATA = {
	GodnessHeroes = {
		item_card_war_of_Kings_special_boss_archer_building = {
			crystalCost = 800,
		},
		item_card_war_of_Kings_special_boss_shaman_building = {
			crystalCost = 800,
		},
		item_card_war_of_Kings_special_boss_rogue_building = {
			crystalCost = 800,
		},
		item_card_war_of_Kings_special_boss_guardian_building = {
			crystalCost = 800,
		},
		item_card_war_of_Kings_special_boss_warrior_building = {
			crystalCost = 800,
		},
		item_card_war_of_Kings_special_boss_mage_building = {
			crystalCost = 800,
		},
	}
}



SHOP_ITEMS = {
	['BasicItems'] = {
		consumables = {
			"item_damage_book",
			'item_amplify_book',
			"item_xp_book",
			"item_xp_book_big",
			"item_clarity_custom",
			"item_shield_buff",
			"item_book_of_soul_creep",			
			"item_flask",
			"item_ward_sentry",
			'item_essence_scepter_custom',
		},
		attributes = {
			"item_book_all_stats",
			"item_book_agility",
			"item_book_strength",
			"item_book_intellect",
			"item_blade_of_alacrity_custom",
			"item_ogre_axe_custom",
			"item_staff_of_wizardry_custom",
		},
		weapons_armor = {
			"item_blight_stone",
			"item_blades_of_attack",
			"item_chainmail",
			"item_quarterstaff",
			"item_helm_of_iron_will",
			"item_javelin",
			"item_broadsword",
			"item_claymore",
			"item_mithril_hammer",
		},
		misc = {
			"item_gloves",
			"item_void_stone",
			"item_ring_of_health",
			"item_void_stone",
			"item_energy_booster",
			"item_point_booster",
			"item_platemail",
			"item_talisman_of_evasion",
			"item_hyperstone",
			"item_ultimate_orb",
			"item_demon_edge",
			"item_mystic_staff_custom_1",
			"item_reaver_custom",
			"item_eagle_custom",
			"item_relic",
		},
	},
	['UpgradeItems'] = {
		basics = {
			"item_null_talisman",
			"item_wraith_band",
			"item_bracer",
			"item_soul_ring",
			"item_power_treads",
			"item_battle_fury_1",
			"item_oblivion_staff",
			"item_pers",
			"item_hand_of_midas_custom",
		},
		support = {
			"item_assault_crimson",
			-- "item_soul_book",
			"item_armor_aura",
		},
		magics	= {
			"item_glimmer_cape",
			"item_veil_of_discord_1",		
			"item_fire_sword",
			"item_aether_lens",
			"item_necronomicon",
			"item_dagon_custom_1",
			"item_cyclone",
			"item_rod_of_atos_custom",
			"item_solar_crest",
			"item_orchid",
			-- "item_essence_scepter_custom",
			"item_nullifier",
			"item_refresher",
			"item_scythe_of_vyse_1",
			"item_octarine_core_1",
			"item_magic_rapier",
		},
		defense = {
			"item_assault_shield",
			"item_shield_blast",
			"item_healing_armor",
			-- "item_soul_booster",
			-- "item_aeon_disk"	,
			-- "item_crimson_guard",		
			-- "item_lotus_orb"	,	
			-- "item_black_king_bar",
			-- "item_hurricane_pike",	
			-- "item_shivas_guard",
			-- "item_manta",
			-- "item_bloodstone",
			-- "item_sphere",
			-- "item_heart",	
			"item_assault",
		},
		weapons = {
			"item_lesser_crit",
			"item_armlet",
			"item_meteor_hammer",
			"item_invis_sword",
			"item_basher",
			"item_monkey_king_bar" ,
			"item_bfury",
			"item_ethereal_blade_1",
			"item_radiance",
			"item_greater_crit",
			"item_butterfly_custom",
			"item_silver_edge",
			"item_abyssal_blade",
			"item_bloodthorn_1",
			"item_fire_sword",
			"item_ice_sword",
			"item_rage_sword",
			"item_rapier",
		},
		artifacts = {
			"item_dragon_lance_custom",
			"item_sange",
	 		"item_yasha",
	 		"item_kaya",
			"item_echo_sabre"	,
	 		"item_maelstrom",
	 		-- "item_diffusal_blade",			
	 		"item_vortex_axe_1",
	 		"item_desolator",
	 		-- "item_kaya_and_sange",
	 		"item_sange_and_yasha",
	 		"item_yasha_and_kaya",
	 		"item_satanic"		,
	 		"item_skadi" ,
	 		"item_kris_of_agony_1",
	 		"item_mjollnir",
	 		'item_mantle_style_custom',
		},
	},
	['UniqueItems'] = {
		tag_warrior = {
			'item_purify_sabre_godness',
			'item_godness_rapier',
		},
		tag_guardian = {
			'item_cuirass_godness',
			'item_healing_ward_godness',
		},
		tag_mage = {
			'item_octarine_core_godness',
			'item_magic_rapier_godness',
			'item_flicker_custom',
			'item_scythe_vyse_godness',
			'item_ethereal_godness',
			'item_rob_of_atos_godness',
			-- 'item_radiance_godness',
			-- 'item_kaya_godness',
		},
		tag_rogue = {
			'item_daedalus_godness',
			'item_godness_desolator',
			'item_monkey_king_bar_godness',
		},
		tag_archer = {
			'item_dragon_lance_godness',
			'item_bloodthorn_godness',
			-- 'item_bow_godness',
		},
	},
}